# InfluxDB
influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb

# Grafana
grafana:
  image: grafana/grafana
  links:
    - influxdb
  ports:
    - "3000:3000"
  volumes:
    - ./data/grafana:/var/lib/grafana

